version: '3'

services:
  cartoon-stylegan:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
